### PR TITLE
Fix related to workflow

### PR DESCRIPTION
**Pull request by TonyStark-47**
### Here, it fixes the autocommenting bot to comment only on the Issue when its related PR gets merged otherwise don't comment at all.

- It also fixes some issue in GSSoC_workflow.yml file where it also labelling the contributor 'gssoc' who is not the Part of GSSoC.

- This PR solves issue #287

### CODE REVIEW

**Comment by growupanand** [comment]
@TonyStark-47 , looks good to me, can you do one minor changes which is related to previous task.

I want to make name pattern of templates same, as you can see bug template have icon after the name. One more thing in the bug template new issue title, currently it have `fix: 🐛 ` , after looking at i found it more related to commit but not a issue title. can you please make it soemthing like you alredy used in previous PR.

image

**Comment by TonyStark-47** [comment]
@growupanand, done 👍

**Comment by growupanand** [comment]
@TonyStark-47 , I am not able to see template for the Infrastructure task.

**Comment by TonyStark-47** [comment]
Hey @growupanand, Is this the required "Infrastructure work" template? Please check it out.

**Comment by TonyStark-47** [comment]
@growupanand, Reverting does not going to help this. There are bugs in workflows which I fixed here. You have to reconsider this.

**Comment by growupanand** [comment]
@TonyStark-47 , After merging the PR there are still some error showing.

image

**Comment by TonyStark-47** [comment]
@growupanand, these error related to commenting on PR creation by github bot, you can see it here:

image

- and error:
image

**Comment by growupanand** [comment]
> @growupanand, these error related to commenting on PR creation by github bot, you can see it here:
> 
> image
> 
> * and error:
>   image
> 
> ### After merging, GitHub's bot does not able to comment, that's why it was showing error.

@TonyStark-47 , can you please create another PR with the fix?

**Pull request merged**
